### ISSUE TITLE
Travis link

### ISSUE THREAD

**Issue by Jfach** [GrantSeltzer/Gitaxis#6]
are you sure you have the correct link for HashiCorp's Membrane? Seems to return a 404.
Reference: https://github.com/GrantSeltzer/Gitaxis/blob/master/.travis.yml

`- go get github.com/hasicorp/membrane`

**Comment by Jfach** [comment]
actually, I can't find HashiCorp's Membrane at all :frowning:

**Comment by GrantSeltzer** [comment]
@Jfach That was a typo, I don't have travis set up properly for Gitaxis right now though. I don't believe it's in a functioning state at the moment regardless.

**Comment by GrantSeltzer** [comment]
@Jfach Development on this will resume when I have more spare time :palm_tree:
